import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import ".././globals.css";
import Header from "./header";
import Footer from "./footer";
import { ClerkProvider } from "@clerk/nextjs";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${font.className} min-h-screen flex flex-col`}>
          <Header />
          <main className="flex flex-col flex-1 items-center justify-center">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
